# DS Intern Work — Project 1

This notebook loads the dataset from this GitHub repo into Colab.

**Steps:** Run each cell top to bottom. If Colab disconnects, rerun from the setup cells.

In [1]:
# Install Excel support (required once per Colab session)
!pip install openpyxl -q

In [2]:
import os
import pandas as pd

REPO_DIR = "/content/DS_intern_work"
DATA_FILE = os.path.join(REPO_DIR, "Dataset for Data Analytics.xlsx")

# Clone the repo if it is not already present
if not os.path.exists(DATA_FILE):
    !git clone https://github.com/kuteesatendojeremiah/DS_intern_work.git

df = pd.read_excel(DATA_FILE)

print(f"Loaded {len(df):,} rows and {len(df.columns)} columns")
df.head()

Cloning into 'DS_intern_work'...
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 21 (delta 9), reused 4 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (21/21), 116.10 KiB | 1.55 MiB/s, done.
Resolving deltas: 100% (9/9), done.
Loaded 1,200 rows and 14 columns

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [3]:
# Quick overview
print("Shape:", df.shape)
print("\nColumns:", list(df.columns))
print("\nMissing values:\n", df.isnull().sum())
df.describe(include="all")

Shape: (1200, 14)

Columns: ['OrderID', 'Date', 'CustomerID', 'Product', 'Quantity', 'UnitPrice', 'ShippingAddress', 'PaymentMethod', 'OrderStatus', 'TrackingNumber', 'ItemsInCart', 'CouponCode', 'ReferralSource', 'TotalPrice']

Missing values:
 OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
count,1200,1200,1200,1200,1200.000000,1200.000000,1200,1200,1200,1200,1200.000000,891,1200,1200.000000
unique,1200,NaN,1189,7,NaN,NaN,655,5,5,1200,NaN,3,5,NaN
top,ORD201183,NaN,C46651,Printer,NaN,NaN,533 Main St,Online,Cancelled,TRK83653396,NaN,FREESHIP,Instagram,NaN
freq,1,NaN,2,181,NaN,NaN,8,258,250,1,NaN,313,259,NaN
mean,NaN,2024-03-22 16:58:48,NaN,NaN,2.945833,356.412750,NaN,NaN,NaN,NaN,5.485000,NaN,NaN,1053.968300
min,NaN,2023-01-01 00:00:00,NaN,NaN,1.000000,11.390000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,11.390000
25%,NaN,2023-08-03 18:00:00,NaN,NaN,2.000000,186.062500,NaN,NaN,NaN,NaN,4.000000,NaN,NaN,410.520000
50%,NaN,2024-03-23 00:00:00,NaN,NaN,3.000000,364.210000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,823.615000
75%,NaN,2024-11-08 12:00:00,NaN,NaN,4.000000,521.570000,NaN,NaN,NaN,NaN,7.000000,NaN,NaN,1578.475000
max,NaN,2025-06-30 00:00:00,NaN,NaN,5.000000,699.930000,NaN,NaN,NaN,NaN,10.000000,NaN,NaN,3456.400000
std,NaN,NaN,NaN,NaN,1.407557,197.177146,NaN,NaN,NaN,NaN,2.281983,NaN,NaN,819.856558

In [4]:
missing_val = df.isnull().mean()
print(missing_val)
cols_to_clean = missing_val[missing_val < 0.05].index
df_cleaned = df.dropna(subset = cols_to_clean)
print(df_cleaned)

OrderID            0.0000
Date               0.0000
CustomerID         0.0000
Product            0.0000
Quantity           0.0000
UnitPrice          0.0000
ShippingAddress    0.0000
PaymentMethod      0.0000
OrderStatus        0.0000
TrackingNumber     0.0000
ItemsInCart        0.0000
CouponCode         0.2575
ReferralSource     0.0000
TotalPrice         0.0000
dtype: float64
        OrderID       Date CustomerID  Product  Quantity  UnitPrice  \
0     ORD200000 2023-01-04     C72649  Monitor         5     570.62
1     ORD200001 2024-08-23     C75739    Phone         2     151.35
2     ORD200002 2024-02-27     C81728   Tablet         5     550.68
3     ORD200003 2023-10-15     C33540    Chair         1     273.19
4     ORD200004 2025-05-08     C81840  Printer         4     626.01
...         ...        ...        ...      ...       ...        ...
1195  ORD201195 2024-06-20     C21126     Desk         1     107.04
1196  ORD201196 2024-03-04     C20095  Monitor         2     662.53
1197  ORD201197 2023-07-13     C79674   Tablet         2     436.84
1198  ORD201198 2024-08-22     C64753    Chair         4     262.52
1199  ORD201199 2023-06-11     C57502   Tablet         4     560.58

     ShippingAddress PaymentMethod OrderStatus TrackingNumber  ItemsInCart  \
0        928 Main St    Debit Card     Shipped    TRK37947903            7
1        823 Main St        Online     Shipped    TRK91186779            3
2        512 Main St   Credit Card   Cancelled    TRK42903982            8
3        275 Main St    Debit Card    Returned    TRK62788070            5
4        668 Main St        Online   Delivered    TRK29241424            8
...              ...           ...         ...            ...          ...
1195     392 Main St   Credit Card   Cancelled    TRK38009181            6
1196     778 Main St        Online   Cancelled    TRK69207593            5
1197     275 Main St        Online   Delivered    TRK88039356            2
1198     509 Main St    Debit Card   Cancelled    TRK71683331            4
1199     201 Main St     Gift Card    Returned    TRK51116746            6

     CouponCode ReferralSource  TotalPrice
0        SAVE10      Instagram     2853.10
1        SAVE10       Referral      302.70
2      FREESHIP          Email     2753.40
3        SAVE10       Facebook      273.19
4        SAVE10          Email     2504.04
...         ...            ...         ...
1195   FREESHIP         Google      107.04
1196        NaN       Facebook     1325.06
1197   FREESHIP      Instagram      873.68
1198   WINTER15      Instagram     1050.08
1199     SAVE10       Referral     2242.32

[1200 rows x 14 columns]

Working on the CouponCode column since it has missing values

In [5]:
mode_coupon_code = df['CouponCode'].mode()[0]
print(f"The mode of 'CouponCode' is: {mode_coupon_code}")
df['CouponCode'] = df['CouponCode'].fillna(mode_coupon_code)
df['CouponCode'].isna().sum()

The mode of 'CouponCode' is: FREESHIP

np.int64(0)

In [6]:
#isolating and neutralizing outliners
import numpy as np
Q1 = df['UnitPrice'].quantile(0.25)
Q3 = df['UnitPrice'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

df['UnitPrice'] = np.clip(df['UnitPrice'], lower_bound, upper_bound)
df['UnitPrice'].min(), df['UnitPrice'].max()
((df['UnitPrice'] < lower_bound) | (df['UnitPrice'] > upper_bound)).sum()

np.int64(0)

## Phase 2: Vectorized Computation Engine - Feature Engineering

Now we'll extract new features from existing columns. Date-based features are often very insightful.

In [7]:
df['Date'] = pd.to_datetime(df['Date'])

df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day
df['DayOfWeek'] = df['Date'].dt.dayofweek # Monday=0, Sunday=6
df['WeekOfYear'] = df['Date'].dt.isocalendar().week.astype(int)
df['DayOfYear'] = df['Date'].dt.dayofyear

print("DataFrame with new date features:")
display(df.head())

DataFrame with new date features:

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice,Year,Month,Day,DayOfWeek,WeekOfYear,DayOfYear
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10,2023,1,4,2,1,4
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70,2024,8,23,4,34,236
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40,2024,2,27,1,9,58
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19,2023,10,15,6,41,288
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04,2025,5,8,3,19,128

### Aggregation-Based Features

creating features by aggregating data based on `Product` and `CustomerID`. These features can reveal patterns in customer behavior and product popularity.

In [8]:
# Feature: Total Quantity Sold per Product
total_quantity_per_product = df.groupby('Product')['Quantity'].sum().rename('TotalQuantitySoldPerProduct').reset_index()
df = df.merge(total_quantity_per_product, on='Product', how='left')

# Feature: Average Unit Price per Product
avg_unit_price_per_product = df.groupby('Product')['UnitPrice'].mean().rename('AverageUnitPricePerProduct').reset_index()
df = df.merge(avg_unit_price_per_product, on='Product', how='left')

# Feature: Number of Orders per Customer
orders_per_customer = df.groupby('CustomerID')['OrderID'].nunique().rename('OrdersPerCustomer').reset_index()
df = df.merge(orders_per_customer, on='CustomerID', how='left')

# Feature: Average Items in Cart per Customer
avg_items_in_cart_per_customer = df.groupby('CustomerID')['ItemsInCart'].mean().rename('AverageItemsInCartPerCustomer').reset_index()
df = df.merge(avg_items_in_cart_per_customer, on='CustomerID', how='left')

print("DataFrame with new aggregation features:")
display(df.head())

DataFrame with new aggregation features:

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,...,Year,Month,Day,DayOfWeek,WeekOfYear,DayOfYear,TotalQuantitySoldPerProduct,AverageUnitPricePerProduct,OrdersPerCustomer,AverageItemsInCartPerCustomer
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,...,2023,1,4,2,1,4,480,358.663620,1,7.0
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,...,2024,8,23,4,34,236,411,375.217564,1,3.0
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,...,2024,2,27,1,9,58,497,367.679106,1,8.0
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,...,2023,10,15,6,41,288,562,355.660281,1,5.0
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,...,2025,5,8,3,19,128,542,351.714917,1,8.0

## Phase 3: Structural Contracts and Scaling

This phase focuses on preparing the data for machine learning models, ensuring it adheres to structural contracts and is scaled appropriately. We'll start by identifying categorical and numerical features.

In [9]:
categorical_cols = df.select_dtypes(include=['object', 'category']).columns.tolist()
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()

print(f"Categorical Columns: {categorical_cols}")
print(f"Numerical Columns: {numerical_cols}")

Categorical Columns: ['OrderID', 'CustomerID', 'Product', 'ShippingAddress', 'PaymentMethod', 'OrderStatus', 'TrackingNumber', 'CouponCode', 'ReferralSource']
Numerical Columns: ['Quantity', 'UnitPrice', 'ItemsInCart', 'TotalPrice', 'WeekOfYear', 'TotalQuantitySoldPerProduct', 'AverageUnitPricePerProduct', 'OrdersPerCustomer', 'AverageItemsInCartPerCustomer']

### Handling High Cardinality Categorical Features (Identifiers)

Columns like `OrderID` and `TrackingNumber` are unique identifiers for each transaction or tracking. They typically don't provide predictive value in their raw form for most machine learning tasks and can create issues with one-hot encoding due to their high cardinality. `CustomerID` was used to create aggregated features, but the original `CustomerID` column itself might not be directly useful as a categorical feature if it has too many unique values and we already have customer-level aggregates. For now, let's remove `OrderID` and `TrackingNumber`.

In [10]:
cols_to_drop_identifiers = ['OrderID', 'TrackingNumber']
df = df.drop(columns=cols_to_drop_identifiers)

# Re-evaluate categorical and numerical columns after dropping identifiers
categorical_cols = df.select_dtypes(include=['object', 'category']).columns.tolist()
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()

print(f"Updated Categorical Columns: {categorical_cols}")
print(f"Updated Numerical Columns: {numerical_cols}")
print("DataFrame head after dropping identifier columns:")
display(df.head())

Updated Categorical Columns: ['CustomerID', 'Product', 'ShippingAddress', 'PaymentMethod', 'OrderStatus', 'CouponCode', 'ReferralSource']
Updated Numerical Columns: ['Quantity', 'UnitPrice', 'ItemsInCart', 'TotalPrice', 'WeekOfYear', 'TotalQuantitySoldPerProduct', 'AverageUnitPricePerProduct', 'OrdersPerCustomer', 'AverageItemsInCartPerCustomer']
DataFrame head after dropping identifier columns:

,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,ItemsInCart,CouponCode,...,Year,Month,Day,DayOfWeek,WeekOfYear,DayOfYear,TotalQuantitySoldPerProduct,AverageUnitPricePerProduct,OrdersPerCustomer,AverageItemsInCartPerCustomer
0,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,7,SAVE10,...,2023,1,4,2,1,4,480,358.663620,1,7.0
1,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,3,SAVE10,...,2024,8,23,4,34,236,411,375.217564,1,3.0
2,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,8,FREESHIP,...,2024,2,27,1,9,58,497,367.679106,1,8.0
3,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,5,SAVE10,...,2023,10,15,6,41,288,562,355.660281,1,5.0
4,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,8,SAVE10,...,2025,5,8,3,19,128,542,351.714917,1,8.0

In [11]:
cols_to_drop_high_cardinality = ['CustomerID', 'ShippingAddress']
df = df.drop(columns=cols_to_drop_high_cardinality)

# Re-evaluate categorical and numerical columns again
categorical_cols = df.select_dtypes(include=['object', 'category']).columns.tolist()
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()

print(f"Final Categorical Columns for Encoding: {categorical_cols}")
print(f"Final Numerical Columns for Scaling: {numerical_cols}")
print("DataFrame head after dropping high-cardinality columns:")
display(df.head())

Final Categorical Columns for Encoding: ['Product', 'PaymentMethod', 'OrderStatus', 'CouponCode', 'ReferralSource']
Final Numerical Columns for Scaling: ['Quantity', 'UnitPrice', 'ItemsInCart', 'TotalPrice', 'WeekOfYear', 'TotalQuantitySoldPerProduct', 'AverageUnitPricePerProduct', 'OrdersPerCustomer', 'AverageItemsInCartPerCustomer']
DataFrame head after dropping high-cardinality columns:

,Date,Product,Quantity,UnitPrice,PaymentMethod,OrderStatus,ItemsInCart,CouponCode,ReferralSource,TotalPrice,Year,Month,Day,DayOfWeek,WeekOfYear,DayOfYear,TotalQuantitySoldPerProduct,AverageUnitPricePerProduct,OrdersPerCustomer,AverageItemsInCartPerCustomer
0,2023-01-04,Monitor,5,570.62,Debit Card,Shipped,7,SAVE10,Instagram,2853.10,2023,1,4,2,1,4,480,358.663620,1,7.0
1,2024-08-23,Phone,2,151.35,Online,Shipped,3,SAVE10,Referral,302.70,2024,8,23,4,34,236,411,375.217564,1,3.0
2,2024-02-27,Tablet,5,550.68,Credit Card,Cancelled,8,FREESHIP,Email,2753.40,2024,2,27,1,9,58,497,367.679106,1,8.0
3,2023-10-15,Chair,1,273.19,Debit Card,Returned,5,SAVE10,Facebook,273.19,2023,10,15,6,41,288,562,355.660281,1,5.0
4,2025-05-08,Printer,4,626.01,Online,Delivered,8,SAVE10,Email,2504.04,2025,5,8,3,19,128,542,351.714917,1,8.0

### Encoding Categorical Features

Now that we've handled high-cardinality identifiers, we can encode the remaining categorical features using one-hot encoding. This converts categorical variables into a numerical format suitable for machine learning algorithms without implying any ordinal relationship.

In [12]:
df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

print("DataFrame head after one-hot encoding:")
display(df_encoded.head())
print(f"New shape of DataFrame: {df_encoded.shape}")

DataFrame head after one-hot encoding:

,Date,Quantity,UnitPrice,ItemsInCart,TotalPrice,Year,Month,Day,DayOfWeek,WeekOfYear,...,OrderStatus_Delivered,OrderStatus_Pending,OrderStatus_Returned,OrderStatus_Shipped,CouponCode_SAVE10,CouponCode_WINTER15,ReferralSource_Facebook,ReferralSource_Google,ReferralSource_Instagram,ReferralSource_Referral
0,2023-01-04,5,570.62,7,2853.10,2023,1,4,2,1,...,False,False,False,True,True,False,False,False,True,False
1,2024-08-23,2,151.35,3,302.70,2024,8,23,4,34,...,False,False,False,True,True,False,False,False,False,True
2,2024-02-27,5,550.68,8,2753.40,2024,2,27,1,9,...,False,False,False,False,False,False,False,False,False,False
3,2023-10-15,1,273.19,5,273.19,2023,10,15,6,41,...,False,False,True,False,True,False,True,False,False,False
4,2025-05-08,4,626.01,8,2504.04,2025,5,8,3,19,...,True,False,False,False,True,False,False,False,False,False

New shape of DataFrame: (1200, 35)

### Scaling Numerical Features

Numerical features often have different scales and ranges, which can negatively impact the performance of many machine learning algorithms. We will use `StandardScaler` to transform these features so they have a mean of 0 and a standard deviation of 1.

In [13]:
from sklearn.preprocessing import StandardScaler

# Identify numerical columns in the encoded DataFrame (excluding 'Date' if it's still present)
# 'Date' column is still present in df_encoded and should not be scaled, so we will drop it first
df_scaled = df_encoded.drop(columns=['Date']).copy()

# Re-identify numerical columns after dropping 'Date'
numerical_cols_final = df_scaled.select_dtypes(include=['int64', 'float64']).columns.tolist()

scaler = StandardScaler()
df_scaled[numerical_cols_final] = scaler.fit_transform(df_scaled[numerical_cols_final])

print("DataFrame head after scaling numerical features:")
display(df_scaled.head())
print(f"Final shape of prepared DataFrame: {df_scaled.shape}")

DataFrame head after scaling numerical features:

,Quantity,UnitPrice,ItemsInCart,TotalPrice,Year,Month,Day,DayOfWeek,WeekOfYear,DayOfYear,...,OrderStatus_Delivered,OrderStatus_Pending,OrderStatus_Returned,OrderStatus_Shipped,CouponCode_SAVE10,CouponCode_WINTER15,ReferralSource_Facebook,ReferralSource_Google,ReferralSource_Instagram,ReferralSource_Referral
0,1.459993,1.086822,0.664173,2.195362,2023,1,4,2,-1.603882,4,...,False,False,False,True,True,False,False,False,True,False
1,-0.672248,-1.040426,-1.089419,-0.916723,2024,8,23,4,0.656715,236,...,False,False,False,True,True,False,False,False,False,True
2,1.459993,0.985653,1.102571,2.073705,2024,2,27,1,-1.055858,58,...,False,False,False,False,False,False,False,False,False,False
3,-1.382995,-0.422247,-0.212623,-0.952732,2023,10,15,6,1.136235,288,...,False,False,True,False,True,False,True,False,False,False
4,0.749246,1.367855,1.102571,1.769427,2025,5,8,3,-0.370829,128,...,True,False,False,False,True,False,False,False,False,False

Final shape of prepared DataFrame: (1200, 34)

In [14]:
from sklearn.preprocessing import StandardScaler

# Identify numerical columns in the encoded DataFrame (excluding 'Date' if it's still present)
# 'Date' column is still present in df_encoded and should not be scaled, so we will drop it first
df_scaled = df_encoded.drop(columns=['Date']).copy()

# Re-identify numerical columns after dropping 'Date'
numerical_cols_final = df_scaled.select_dtypes(include=['int64', 'float64']).columns.tolist()

scaler = StandardScaler()
df_scaled[numerical_cols_final] = scaler.fit_transform(df_scaled[numerical_cols_final])

print("DataFrame head after scaling numerical features:")
display(df_scaled.head())
print(f"Final shape of prepared DataFrame: {df_scaled.shape}")

DataFrame head after scaling numerical features:

,Quantity,UnitPrice,ItemsInCart,TotalPrice,Year,Month,Day,DayOfWeek,WeekOfYear,DayOfYear,...,OrderStatus_Delivered,OrderStatus_Pending,OrderStatus_Returned,OrderStatus_Shipped,CouponCode_SAVE10,CouponCode_WINTER15,ReferralSource_Facebook,ReferralSource_Google,ReferralSource_Instagram,ReferralSource_Referral
0,1.459993,1.086822,0.664173,2.195362,2023,1,4,2,-1.603882,4,...,False,False,False,True,True,False,False,False,True,False
1,-0.672248,-1.040426,-1.089419,-0.916723,2024,8,23,4,0.656715,236,...,False,False,False,True,True,False,False,False,False,True
2,1.459993,0.985653,1.102571,2.073705,2024,2,27,1,-1.055858,58,...,False,False,False,False,False,False,False,False,False,False
3,-1.382995,-0.422247,-0.212623,-0.952732,2023,10,15,6,1.136235,288,...,False,False,True,False,True,False,True,False,False,False
4,0.749246,1.367855,1.102571,1.769427,2025,5,8,3,-0.370829,128,...,True,False,False,False,True,False,False,False,False,False

Final shape of prepared DataFrame: (1200, 34)

### Saving the Prepared Data

Now, we'll save the `df_scaled` DataFrame to a CSV file. This file can then be easily loaded into another notebook for further analysis or model building in 'Project 2'.

In [16]:
output_file_path = os.path.join(REPO_DIR, 'prepared_data_for_project2.csv')
df_scaled.to_csv(output_file_path, index=False)

print(f"'df_scaled' DataFrame saved to {output_file_path}")

'df_scaled' DataFrame saved to /content/DS_intern_work/prepared_data_for_project2.csv